# Generated by Django 5.0.3 on 2024-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('only_app', '0003_product_if_notif_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(to='only_app.product'),
        ),
    ]
