# Generated by Django 5.0.3 on 2024-04-13 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('only_app', '0007_stock_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Promocode',
        ),
    ]
