# Generated by Django 5.0.3 on 2024-04-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('only_app', '0008_delete_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='if_notif_sent',
        ),
        migrations.AddField(
            model_name='stock',
            name='if_notif_sent',
            field=models.BooleanField(default=False),
        ),
    ]
